[package]
name = "temporal-php-bridge"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "temporal_php_bridge"
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
mimalloc = { version = "0.1", default-features = false }
futures-util = "0.3"
prost = "0.14"
serde_json = "1.0"
tokio = { version = "1", default-features = false, features = ["rt", "time"] }
temporalio-sdk-core = { git = "https://github.com/temporalio/sdk-core.git", rev = "2872b5363e1b745cfb90313ebc7a507c5d25c398" }
temporalio-client = { git = "https://github.com/temporalio/sdk-core.git", rev = "2872b5363e1b745cfb90313ebc7a507c5d25c398" }
temporalio-common = { git = "https://github.com/temporalio/sdk-core.git", rev = "2872b5363e1b745cfb90313ebc7a507c5d25c398", features = ["core-based-sdk"] }

[build-dependencies]
cbindgen = { version = "0.29", default-features = false }

[profile.release]
strip = false
lto = "fat"
codegen-units = 1
