<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace Temporal\Tests\Proto\ProtobufMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
s

test.prototests"
Test
value (	B?ÊTemporal\\Tests\\Protoâ%Temporal\\Tests\\Proto\\ProtobufMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

