<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/workflow/v1/message.proto

namespace Temporal\Api\Workflow\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.workflow.v1.PendingActivityInfo</code>
 */
class PendingActivityInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string activity_id = 1;</code>
     */
    protected $activity_id = '';
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.ActivityType activity_type = 2;</code>
     */
    protected $activity_type = null;
    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.PendingActivityState state = 3;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads heartbeat_details = 4;</code>
     */
    protected $heartbeat_details = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_heartbeat_time = 5 [(.gogoproto.stdtime) = true];</code>
     */
    protected $last_heartbeat_time = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_started_time = 6 [(.gogoproto.stdtime) = true];</code>
     */
    protected $last_started_time = null;
    /**
     * Generated from protobuf field <code>int32 attempt = 7;</code>
     */
    protected $attempt = 0;
    /**
     * Generated from protobuf field <code>int32 maximum_attempts = 8;</code>
     */
    protected $maximum_attempts = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_time = 9 [(.gogoproto.stdtime) = true];</code>
     */
    protected $scheduled_time = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expiration_time = 10 [(.gogoproto.stdtime) = true];</code>
     */
    protected $expiration_time = null;
    /**
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure last_failure = 11;</code>
     */
    protected $last_failure = null;
    /**
     * Generated from protobuf field <code>string last_worker_identity = 12;</code>
     */
    protected $last_worker_identity = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $activity_id
     *     @type \Temporal\Api\Common\V1\ActivityType $activity_type
     *     @type int $state
     *     @type \Temporal\Api\Common\V1\Payloads $heartbeat_details
     *     @type \Google\Protobuf\Timestamp $last_heartbeat_time
     *     @type \Google\Protobuf\Timestamp $last_started_time
     *     @type int $attempt
     *     @type int $maximum_attempts
     *     @type \Google\Protobuf\Timestamp $scheduled_time
     *     @type \Google\Protobuf\Timestamp $expiration_time
     *     @type \Temporal\Api\Failure\V1\Failure $last_failure
     *     @type string $last_worker_identity
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflow\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string activity_id = 1;</code>
     * @return string
     */
    public function getActivityId()
    {
        return $this->activity_id;
    }

    /**
     * Generated from protobuf field <code>string activity_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->activity_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.ActivityType activity_type = 2;</code>
     * @return \Temporal\Api\Common\V1\ActivityType|null
     */
    public function getActivityType()
    {
        return $this->activity_type;
    }

    public function hasActivityType()
    {
        return isset($this->activity_type);
    }

    public function clearActivityType()
    {
        unset($this->activity_type);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.ActivityType activity_type = 2;</code>
     * @param \Temporal\Api\Common\V1\ActivityType $var
     * @return $this
     */
    public function setActivityType($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\ActivityType::class);
        $this->activity_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.PendingActivityState state = 3;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.enums.v1.PendingActivityState state = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\PendingActivityState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads heartbeat_details = 4;</code>
     * @return \Temporal\Api\Common\V1\Payloads|null
     */
    public function getHeartbeatDetails()
    {
        return $this->heartbeat_details;
    }

    public function hasHeartbeatDetails()
    {
        return isset($this->heartbeat_details);
    }

    public function clearHeartbeatDetails()
    {
        unset($this->heartbeat_details);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.Payloads heartbeat_details = 4;</code>
     * @param \Temporal\Api\Common\V1\Payloads $var
     * @return $this
     */
    public function setHeartbeatDetails($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\Payloads::class);
        $this->heartbeat_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_heartbeat_time = 5 [(.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLastHeartbeatTime()
    {
        return $this->last_heartbeat_time;
    }

    public function hasLastHeartbeatTime()
    {
        return isset($this->last_heartbeat_time);
    }

    public function clearLastHeartbeatTime()
    {
        unset($this->last_heartbeat_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_heartbeat_time = 5 [(.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastHeartbeatTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_heartbeat_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_started_time = 6 [(.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLastStartedTime()
    {
        return $this->last_started_time;
    }

    public function hasLastStartedTime()
    {
        return isset($this->last_started_time);
    }

    public function clearLastStartedTime()
    {
        unset($this->last_started_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_started_time = 6 [(.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastStartedTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_started_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 attempt = 7;</code>
     * @return int
     */
    public function getAttempt()
    {
        return $this->attempt;
    }

    /**
     * Generated from protobuf field <code>int32 attempt = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAttempt($var)
    {
        GPBUtil::checkInt32($var);
        $this->attempt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 maximum_attempts = 8;</code>
     * @return int
     */
    public function getMaximumAttempts()
    {
        return $this->maximum_attempts;
    }

    /**
     * Generated from protobuf field <code>int32 maximum_attempts = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMaximumAttempts($var)
    {
        GPBUtil::checkInt32($var);
        $this->maximum_attempts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_time = 9 [(.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getScheduledTime()
    {
        return $this->scheduled_time;
    }

    public function hasScheduledTime()
    {
        return isset($this->scheduled_time);
    }

    public function clearScheduledTime()
    {
        unset($this->scheduled_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduled_time = 9 [(.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setScheduledTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->scheduled_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expiration_time = 10 [(.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getExpirationTime()
    {
        return $this->expiration_time;
    }

    public function hasExpirationTime()
    {
        return isset($this->expiration_time);
    }

    public function clearExpirationTime()
    {
        unset($this->expiration_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expiration_time = 10 [(.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setExpirationTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->expiration_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure last_failure = 11;</code>
     * @return \Temporal\Api\Failure\V1\Failure|null
     */
    public function getLastFailure()
    {
        return $this->last_failure;
    }

    public function hasLastFailure()
    {
        return isset($this->last_failure);
    }

    public function clearLastFailure()
    {
        unset($this->last_failure);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.failure.v1.Failure last_failure = 11;</code>
     * @param \Temporal\Api\Failure\V1\Failure $var
     * @return $this
     */
    public function setLastFailure($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Failure\V1\Failure::class);
        $this->last_failure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_worker_identity = 12;</code>
     * @return string
     */
    public function getLastWorkerIdentity()
    {
        return $this->last_worker_identity;
    }

    /**
     * Generated from protobuf field <code>string last_worker_identity = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setLastWorkerIdentity($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_worker_identity = $var;

        return $this;
    }

}

