version: "3"

rpc:
    listen: ${BENCH_RR_RPC:-tcp://127.0.0.1:6556}

server:
    command: "php -dopcache.enable_cli=1 -dxdebug.mode=off -dpcov.enabled=0 worker.php"

temporal:
    address: ${TEMPORAL_ADDRESS:-127.0.0.1:7557}
    namespace: default
    activities:
        num_workers: ${BENCH_ACTIVITY_WORKERS:-4}

logs:
    level: error
