<?php

declare(strict_types=1);

namespace Grpc;

if (\extension_loaded('grpc')) {
    return;
}

const CALL_OK = 0;
const CALL_ERROR = 1;
const CALL_ERROR_NOT_ON_SERVER = 2;
const CALL_ERROR_NOT_ON_CLIENT = 3;
const CALL_ERROR_ALREADY_INVOKED = 5;
const CALL_ERROR_NOT_INVOKED = 6;
const CALL_ERROR_ALREADY_FINISHED = 7;
const CALL_ERROR_TOO_MANY_OPERATIONS = 8;
const CALL_ERROR_INVALID_FLAGS = 9;
const STATUS_OK = 0;
const STATUS_CANCELLED = 1;
const STATUS_UNKNOWN = 2;
const STATUS_INVALID_ARGUMENT = 3;
const STATUS_DEADLINE_EXCEEDED = 4;
const STATUS_NOT_FOUND = 5;
const STATUS_ALREADY_EXISTS = 6;
const STATUS_PERMISSION_DENIED = 7;
const STATUS_UNAUTHENTICATED = 16;
const STATUS_RESOURCE_EXHAUSTED = 8;
const STATUS_FAILED_PRECONDITION = 9;
const STATUS_ABORTED = 10;
const STATUS_OUT_OF_RANGE = 11;
const STATUS_UNIMPLEMENTED = 12;
const STATUS_INTERNAL = 13;
const STATUS_UNAVAILABLE = 14;
const STATUS_DATA_LOSS = 15;
const OP_SEND_INITIAL_METADATA = 0;
const OP_SEND_MESSAGE = 1;
const OP_SEND_CLOSE_FROM_CLIENT = 2;
const OP_SEND_STATUS_FROM_SERVER = 3;
const OP_RECV_INITIAL_METADATA = 4;
const OP_RECV_MESSAGE = 5;
const OP_RECV_STATUS_ON_CLIENT = 6;
const OP_RECV_CLOSE_ON_SERVER = 7;
const CHANNEL_IDLE = 0;
const CHANNEL_CONNECTING = 1;
const CHANNEL_READY = 2;
const CHANNEL_TRANSIENT_FAILURE = 3;
const CHANNEL_FATAL_FAILURE = 4;
