<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1\UpdateWorkerBuildIdCompatibilityRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.UpdateWorkerBuildIdCompatibilityRequest.MergeSets</code>
 */
class MergeSets extends \Google\Protobuf\Internal\Message
{
    /**
     * A build ID in the set whose default will become the merged set default
     *
     * Generated from protobuf field <code>string primary_set_build_id = 1;</code>
     */
    protected $primary_set_build_id = '';
    /**
     * A build ID in the set which will be merged into the primary set
     *
     * Generated from protobuf field <code>string secondary_set_build_id = 2;</code>
     */
    protected $secondary_set_build_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $primary_set_build_id
     *           A build ID in the set whose default will become the merged set default
     *     @type string $secondary_set_build_id
     *           A build ID in the set which will be merged into the primary set
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * A build ID in the set whose default will become the merged set default
     *
     * Generated from protobuf field <code>string primary_set_build_id = 1;</code>
     * @return string
     */
    public function getPrimarySetBuildId()
    {
        return $this->primary_set_build_id;
    }

    /**
     * A build ID in the set whose default will become the merged set default
     *
     * Generated from protobuf field <code>string primary_set_build_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimarySetBuildId($var)
    {
        GPBUtil::checkString($var, True);
        $this->primary_set_build_id = $var;

        return $this;
    }

    /**
     * A build ID in the set which will be merged into the primary set
     *
     * Generated from protobuf field <code>string secondary_set_build_id = 2;</code>
     * @return string
     */
    public function getSecondarySetBuildId()
    {
        return $this->secondary_set_build_id;
    }

    /**
     * A build ID in the set which will be merged into the primary set
     *
     * Generated from protobuf field <code>string secondary_set_build_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSecondarySetBuildId($var)
    {
        GPBUtil::checkString($var, True);
        $this->secondary_set_build_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MergeSets::class, \Temporal\Api\Workflowservice\V1\UpdateWorkerBuildIdCompatibilityRequest_MergeSets::class);

