<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/taskqueue/v1/message.proto

namespace Temporal\Api\Taskqueue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * See https://docs.temporal.io/docs/concepts/task-queues/
 *
 * Generated from protobuf message <code>temporal.api.taskqueue.v1.TaskQueue</code>
 */
class TaskQueue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Default: TASK_QUEUE_KIND_NORMAL.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.TaskQueueKind kind = 2;</code>
     */
    protected $kind = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $kind
     *           Default: TASK_QUEUE_KIND_NORMAL.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Taskqueue\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Default: TASK_QUEUE_KIND_NORMAL.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.TaskQueueKind kind = 2;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Default: TASK_QUEUE_KIND_NORMAL.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.TaskQueueKind kind = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\TaskQueueKind::class);
        $this->kind = $var;

        return $this;
    }

}

