<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.GetWorkerBuildIdCompatibilityResponse</code>
 */
class GetWorkerBuildIdCompatibilityResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Major version sets, in order from oldest to newest. The last element of the list will always
     * be the current default major version. IE: New workflows will target the most recent version
     * in that version set.
     * There may be fewer sets returned than exist, if the request chose to limit this response.
     *
     * Generated from protobuf field <code>repeated .temporal.api.taskqueue.v1.CompatibleVersionSet major_version_sets = 1;</code>
     */
    private $major_version_sets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Temporal\Api\Taskqueue\V1\CompatibleVersionSet>|\Google\Protobuf\Internal\RepeatedField $major_version_sets
     *           Major version sets, in order from oldest to newest. The last element of the list will always
     *           be the current default major version. IE: New workflows will target the most recent version
     *           in that version set.
     *           There may be fewer sets returned than exist, if the request chose to limit this response.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Major version sets, in order from oldest to newest. The last element of the list will always
     * be the current default major version. IE: New workflows will target the most recent version
     * in that version set.
     * There may be fewer sets returned than exist, if the request chose to limit this response.
     *
     * Generated from protobuf field <code>repeated .temporal.api.taskqueue.v1.CompatibleVersionSet major_version_sets = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMajorVersionSets()
    {
        return $this->major_version_sets;
    }

    /**
     * Major version sets, in order from oldest to newest. The last element of the list will always
     * be the current default major version. IE: New workflows will target the most recent version
     * in that version set.
     * There may be fewer sets returned than exist, if the request chose to limit this response.
     *
     * Generated from protobuf field <code>repeated .temporal.api.taskqueue.v1.CompatibleVersionSet major_version_sets = 1;</code>
     * @param array<\Temporal\Api\Taskqueue\V1\CompatibleVersionSet>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMajorVersionSets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Taskqueue\V1\CompatibleVersionSet::class);
        $this->major_version_sets = $arr;

        return $this;
    }

}

