<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.ListClosedWorkflowExecutionsRequest</code>
 */
class ListClosedWorkflowExecutionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>int32 maximum_page_size = 2;</code>
     */
    protected $maximum_page_size = 0;
    /**
     * Generated from protobuf field <code>bytes next_page_token = 3;</code>
     */
    protected $next_page_token = '';
    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.StartTimeFilter start_time_filter = 4;</code>
     */
    protected $start_time_filter = null;
    protected $filters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type int $maximum_page_size
     *     @type string $next_page_token
     *     @type \Temporal\Api\Filter\V1\StartTimeFilter $start_time_filter
     *     @type \Temporal\Api\Filter\V1\WorkflowExecutionFilter $execution_filter
     *     @type \Temporal\Api\Filter\V1\WorkflowTypeFilter $type_filter
     *     @type \Temporal\Api\Filter\V1\StatusFilter $status_filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 maximum_page_size = 2;</code>
     * @return int
     */
    public function getMaximumPageSize()
    {
        return $this->maximum_page_size;
    }

    /**
     * Generated from protobuf field <code>int32 maximum_page_size = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaximumPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->maximum_page_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes next_page_token = 3;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Generated from protobuf field <code>bytes next_page_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->next_page_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.StartTimeFilter start_time_filter = 4;</code>
     * @return \Temporal\Api\Filter\V1\StartTimeFilter|null
     */
    public function getStartTimeFilter()
    {
        return $this->start_time_filter;
    }

    public function hasStartTimeFilter()
    {
        return isset($this->start_time_filter);
    }

    public function clearStartTimeFilter()
    {
        unset($this->start_time_filter);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.StartTimeFilter start_time_filter = 4;</code>
     * @param \Temporal\Api\Filter\V1\StartTimeFilter $var
     * @return $this
     */
    public function setStartTimeFilter($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Filter\V1\StartTimeFilter::class);
        $this->start_time_filter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.WorkflowExecutionFilter execution_filter = 5;</code>
     * @return \Temporal\Api\Filter\V1\WorkflowExecutionFilter|null
     */
    public function getExecutionFilter()
    {
        return $this->readOneof(5);
    }

    public function hasExecutionFilter()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.WorkflowExecutionFilter execution_filter = 5;</code>
     * @param \Temporal\Api\Filter\V1\WorkflowExecutionFilter $var
     * @return $this
     */
    public function setExecutionFilter($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Filter\V1\WorkflowExecutionFilter::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.WorkflowTypeFilter type_filter = 6;</code>
     * @return \Temporal\Api\Filter\V1\WorkflowTypeFilter|null
     */
    public function getTypeFilter()
    {
        return $this->readOneof(6);
    }

    public function hasTypeFilter()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.WorkflowTypeFilter type_filter = 6;</code>
     * @param \Temporal\Api\Filter\V1\WorkflowTypeFilter $var
     * @return $this
     */
    public function setTypeFilter($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Filter\V1\WorkflowTypeFilter::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.StatusFilter status_filter = 7;</code>
     * @return \Temporal\Api\Filter\V1\StatusFilter|null
     */
    public function getStatusFilter()
    {
        return $this->readOneof(7);
    }

    public function hasStatusFilter()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.filter.v1.StatusFilter status_filter = 7;</code>
     * @param \Temporal\Api\Filter\V1\StatusFilter $var
     * @return $this
     */
    public function setStatusFilter($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Filter\V1\StatusFilter::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getFilters()
    {
        return $this->whichOneof("filters");
    }

}

