<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/workflowservice/v1/request_response.proto

namespace Temporal\Api\Workflowservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.workflowservice.v1.QueryWorkflowRequest</code>
 */
class QueryWorkflowRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowExecution execution = 2;</code>
     */
    protected $execution = null;
    /**
     * Generated from protobuf field <code>.temporal.api.query.v1.WorkflowQuery query = 3;</code>
     */
    protected $query = null;
    /**
     * QueryRejectCondition can used to reject the query if workflow state does not satisfy condition.
     * Default: QUERY_REJECT_CONDITION_NONE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.QueryRejectCondition query_reject_condition = 4;</code>
     */
    protected $query_reject_condition = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type \Temporal\Api\Common\V1\WorkflowExecution $execution
     *     @type \Temporal\Api\Query\V1\WorkflowQuery $query
     *     @type int $query_reject_condition
     *           QueryRejectCondition can used to reject the query if workflow state does not satisfy condition.
     *           Default: QUERY_REJECT_CONDITION_NONE.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Workflowservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowExecution execution = 2;</code>
     * @return \Temporal\Api\Common\V1\WorkflowExecution|null
     */
    public function getExecution()
    {
        return $this->execution;
    }

    public function hasExecution()
    {
        return isset($this->execution);
    }

    public function clearExecution()
    {
        unset($this->execution);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.common.v1.WorkflowExecution execution = 2;</code>
     * @param \Temporal\Api\Common\V1\WorkflowExecution $var
     * @return $this
     */
    public function setExecution($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Common\V1\WorkflowExecution::class);
        $this->execution = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.temporal.api.query.v1.WorkflowQuery query = 3;</code>
     * @return \Temporal\Api\Query\V1\WorkflowQuery|null
     */
    public function getQuery()
    {
        return $this->query;
    }

    public function hasQuery()
    {
        return isset($this->query);
    }

    public function clearQuery()
    {
        unset($this->query);
    }

    /**
     * Generated from protobuf field <code>.temporal.api.query.v1.WorkflowQuery query = 3;</code>
     * @param \Temporal\Api\Query\V1\WorkflowQuery $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Query\V1\WorkflowQuery::class);
        $this->query = $var;

        return $this;
    }

    /**
     * QueryRejectCondition can used to reject the query if workflow state does not satisfy condition.
     * Default: QUERY_REJECT_CONDITION_NONE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.QueryRejectCondition query_reject_condition = 4;</code>
     * @return int
     */
    public function getQueryRejectCondition()
    {
        return $this->query_reject_condition;
    }

    /**
     * QueryRejectCondition can used to reject the query if workflow state does not satisfy condition.
     * Default: QUERY_REJECT_CONDITION_NONE.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.QueryRejectCondition query_reject_condition = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setQueryRejectCondition($var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\QueryRejectCondition::class);
        $this->query_reject_condition = $var;

        return $this;
    }

}

