<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/workflowservice/v1/request_response.proto

namespace GPBMetadata\Temporal\Api\Workflowservice\V1;

class RequestResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Temporal\Api\Enums\V1\BatchOperation::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\Workflow::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\PBNamespace::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\FailedCause::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\Common::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\Query::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\Reset::initOnce();
        \GPBMetadata\Temporal\Api\Enums\V1\TaskQueue::initOnce();
        \GPBMetadata\Temporal\Api\Common\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\History\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Workflow\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Command\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Failure\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Filter\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Protocol\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\PBNamespace\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Query\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Replication\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Schedule\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Taskqueue\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Update\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Version\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Batch\V1\Message::initOnce();
        \GPBMetadata\Temporal\Api\Sdk\V1\TaskCompleteMetadata::initOnce();
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Dependencies\Gogoproto\Gogo::initOnce();
        $pool->internalAddGeneratedFile(
            '
Õπ
6temporal/api/workflowservice/v1/request_response.prototemporal.api.workflowservice.v1$temporal/api/enums/v1/workflow.proto%temporal/api/enums/v1/namespace.proto(temporal/api/enums/v1/failed_cause.proto"temporal/api/enums/v1/common.proto!temporal/api/enums/v1/query.proto!temporal/api/enums/v1/reset.proto&temporal/api/enums/v1/task_queue.proto$temporal/api/common/v1/message.proto%temporal/api/history/v1/message.proto&temporal/api/workflow/v1/message.proto%temporal/api/command/v1/message.proto%temporal/api/failure/v1/message.proto$temporal/api/filter/v1/message.proto&temporal/api/protocol/v1/message.proto\'temporal/api/namespace/v1/message.proto#temporal/api/query/v1/message.proto)temporal/api/replication/v1/message.proto&temporal/api/schedule/v1/message.proto\'temporal/api/taskqueue/v1/message.proto$temporal/api/update/v1/message.proto%temporal/api/version/v1/message.proto#temporal/api/batch/v1/message.proto0temporal/api/sdk/v1/task_complete_metadata.protogoogle/protobuf/duration.protogoogle/protobuf/timestamp.proto!dependencies/gogoproto/gogo.proto"é
RegisterNamespaceRequest
	namespace (	
description (	
owner_email (	L
#workflow_execution_retention_period (2.google.protobuf.DurationBòﬂG
clusters (25.temporal.api.replication.v1.ClusterReplicationConfig
active_cluster_name (	Q
data (2C.temporal.api.workflowservice.v1.RegisterNamespaceRequest.DataEntry
security_token (	
is_global_namespace	 (D
history_archival_state
 (2$.temporal.api.enums.v1.ArchivalState
history_archival_uri (	G
visibility_archival_state (2$.temporal.api.enums.v1.ArchivalState
visibility_archival_uri (	+
	DataEntry
key (	
value (	:8"
RegisterNamespaceResponse"â
ListNamespacesRequest
	page_size (
next_page_token (D
namespace_filter (2*.temporal.api.namespace.v1.NamespaceFilter"Å
ListNamespacesResponseN

namespaces (2:.temporal.api.workflowservice.v1.DescribeNamespaceResponse
next_page_token ("9
DescribeNamespaceRequest
	namespace (	

id (	"Ï
DescribeNamespaceResponse@
namespace_info (2(.temporal.api.namespace.v1.NamespaceInfo:
config (2*.temporal.api.namespace.v1.NamespaceConfigS
replication_config (27.temporal.api.replication.v1.NamespaceReplicationConfig
failover_version (
is_global_namespace (E
failover_history (2+.temporal.api.replication.v1.FailoverStatus"œ
UpdateNamespaceRequest
	namespace (	C
update_info (2..temporal.api.namespace.v1.UpdateNamespaceInfo:
config (2*.temporal.api.namespace.v1.NamespaceConfigS
replication_config (27.temporal.api.replication.v1.NamespaceReplicationConfig
security_token (	
delete_bad_binary (	
promote_namespace ("£
UpdateNamespaceResponse@
namespace_info (2(.temporal.api.namespace.v1.NamespaceInfo:
config (2*.temporal.api.namespace.v1.NamespaceConfigS
replication_config (27.temporal.api.replication.v1.NamespaceReplicationConfig
failover_version (
is_global_namespace ("F
DeprecateNamespaceRequest
	namespace (	
security_token (	"
DeprecateNamespaceResponse"˚
StartWorkflowExecutionRequest
	namespace (	
workflow_id (	;
workflow_type (2$.temporal.api.common.v1.WorkflowType8

task_queue (2$.temporal.api.taskqueue.v1.TaskQueue/
input (2 .temporal.api.common.v1.PayloadsC
workflow_execution_timeout (2.google.protobuf.DurationBòﬂ=
workflow_run_timeout (2.google.protobuf.DurationBòﬂ>
workflow_task_timeout (2.google.protobuf.DurationBòﬂ
identity	 (	

request_id
 (	N
workflow_id_reuse_policy (2,.temporal.api.enums.v1.WorkflowIdReusePolicy9
retry_policy (2#.temporal.api.common.v1.RetryPolicy
cron_schedule (	*
memo (2.temporal.api.common.v1.MemoC
search_attributes (2(.temporal.api.common.v1.SearchAttributes.
header (2.temporal.api.common.v1.Header
request_eager_execution (;
continued_failure (2 .temporal.api.failure.v1.Failure@
last_completion_result (2 .temporal.api.common.v1.Payloads=
workflow_start_delay (2.google.protobuf.DurationBòﬂ"ç
StartWorkflowExecutionResponse
run_id (	[
eager_workflow_task (2>.temporal.api.workflowservice.v1.PollWorkflowTaskQueueResponse"™
"GetWorkflowExecutionHistoryRequest
	namespace (	<
	execution (2).temporal.api.common.v1.WorkflowExecution
maximum_page_size (
next_page_token (
wait_new_event (P
history_event_filter_type (2-.temporal.api.enums.v1.HistoryEventFilterType
skip_archival ("∫
#GetWorkflowExecutionHistoryResponse1
history (2 .temporal.api.history.v1.History5
raw_history (2 .temporal.api.common.v1.DataBlob
next_page_token (
archived ("∞
)GetWorkflowExecutionHistoryReverseRequest
	namespace (	<
	execution (2).temporal.api.common.v1.WorkflowExecution
maximum_page_size (
next_page_token ("x
*GetWorkflowExecutionHistoryReverseResponse1
history (2 .temporal.api.history.v1.History
next_page_token ("Ó
PollWorkflowTaskQueueRequest
	namespace (	8

task_queue (2$.temporal.api.taskqueue.v1.TaskQueue
identity (	
binary_checksum (	V
worker_version_capabilities (21.temporal.api.common.v1.WorkerVersionCapabilities" 
PollWorkflowTaskQueueResponse

task_token (E
workflow_execution (2).temporal.api.common.v1.WorkflowExecution;
workflow_type (2$.temporal.api.common.v1.WorkflowType!
previous_started_event_id (
started_event_id (
attempt (
backlog_count_hint (1
history (2 .temporal.api.history.v1.History
next_page_token	 (3
query
 (2$.temporal.api.query.v1.WorkflowQueryK
workflow_execution_task_queue (2$.temporal.api.taskqueue.v1.TaskQueue8
scheduled_time (2.google.protobuf.TimestampBêﬂ6
started_time (2.google.protobuf.TimestampBêﬂ\\
queries (2K.temporal.api.workflowservice.v1.PollWorkflowTaskQueueResponse.QueriesEntry3
messages (2!.temporal.api.protocol.v1.MessageT
QueriesEntry
key (	3
value (2$.temporal.api.query.v1.WorkflowQuery:8"§
#RespondWorkflowTaskCompletedRequest

task_token (2
commands (2 .temporal.api.command.v1.Command
identity (	O
sticky_attributes (24.temporal.api.taskqueue.v1.StickyExecutionAttributes 
return_new_workflow_task (&
force_create_new_workflow_task (
binary_checksum (	m
query_results (2V.temporal.api.workflowservice.v1.RespondWorkflowTaskCompletedRequest.QueryResultsEntry
	namespace	 (	H
worker_version_stamp
 (2*.temporal.api.common.v1.WorkerVersionStamp3
messages (2!.temporal.api.protocol.v1.MessageH
sdk_metadata (22.temporal.api.sdk.v1.WorkflowTaskCompletedMetadataC
metering_metadata (2(.temporal.api.common.v1.MeteringMetadata_
QueryResultsEntry
key (	9
value (2*.temporal.api.query.v1.WorkflowQueryResult:8"ı
$RespondWorkflowTaskCompletedResponseU
workflow_task (2>.temporal.api.workflowservice.v1.PollWorkflowTaskQueueResponseV
activity_tasks (2>.temporal.api.workflowservice.v1.PollActivityTaskQueueResponse
reset_history_event_id ("ﬂ
 RespondWorkflowTaskFailedRequest

task_token (=
cause (2..temporal.api.enums.v1.WorkflowTaskFailedCause1
failure (2 .temporal.api.failure.v1.Failure
identity (	
binary_checksum (	
	namespace (	3
messages (2!.temporal.api.protocol.v1.MessageB
worker_version (2*.temporal.api.common.v1.WorkerVersionStamp"#
!RespondWorkflowTaskFailedResponse"†
PollActivityTaskQueueRequest
	namespace (	8

task_queue (2$.temporal.api.taskqueue.v1.TaskQueue
identity (	I
task_queue_metadata (2,.temporal.api.taskqueue.v1.TaskQueueMetadataV
worker_version_capabilities (21.temporal.api.common.v1.WorkerVersionCapabilities"å
PollActivityTaskQueueResponse

task_token (
workflow_namespace (	;
workflow_type (2$.temporal.api.common.v1.WorkflowTypeE
workflow_execution (2).temporal.api.common.v1.WorkflowExecution;
activity_type (2$.temporal.api.common.v1.ActivityType
activity_id (	.
header (2.temporal.api.common.v1.Header/
input (2 .temporal.api.common.v1.Payloads;
heartbeat_details	 (2 .temporal.api.common.v1.Payloads8
scheduled_time
 (2.google.protobuf.TimestampBêﬂH
current_attempt_scheduled_time (2.google.protobuf.TimestampBêﬂ6
started_time (2.google.protobuf.TimestampBêﬂ
attempt (B
schedule_to_close_timeout (2.google.protobuf.DurationBòﬂ?
start_to_close_timeout (2.google.protobuf.DurationBòﬂ:
heartbeat_timeout (2.google.protobuf.DurationBòﬂ9
retry_policy (2#.temporal.api.common.v1.RetryPolicy"ê
"RecordActivityTaskHeartbeatRequest

task_token (1
details (2 .temporal.api.common.v1.Payloads
identity (	
	namespace (	"?
#RecordActivityTaskHeartbeatResponse
cancel_requested ("∫
&RecordActivityTaskHeartbeatByIdRequest
	namespace (	
workflow_id (	
run_id (	
activity_id (	1
details (2 .temporal.api.common.v1.Payloads
identity (	"C
\'RecordActivityTaskHeartbeatByIdResponse
cancel_requested ("‘
#RespondActivityTaskCompletedRequest

task_token (0
result (2 .temporal.api.common.v1.Payloads
identity (	
	namespace (	B
worker_version (2*.temporal.api.common.v1.WorkerVersionStamp"&
$RespondActivityTaskCompletedResponse"∫
\'RespondActivityTaskCompletedByIdRequest
	namespace (	
workflow_id (	
run_id (	
activity_id (	0
result (2 .temporal.api.common.v1.Payloads
identity (	"*
(RespondActivityTaskCompletedByIdResponse"î
 RespondActivityTaskFailedRequest

task_token (1
failure (2 .temporal.api.failure.v1.Failure
identity (	
	namespace (	@
last_heartbeat_details (2 .temporal.api.common.v1.PayloadsB
worker_version (2*.temporal.api.common.v1.WorkerVersionStamp"W
!RespondActivityTaskFailedResponse2
failures (2 .temporal.api.failure.v1.Failure"˙
$RespondActivityTaskFailedByIdRequest
	namespace (	
workflow_id (	
run_id (	
activity_id (	1
failure (2 .temporal.api.failure.v1.Failure
identity (	@
last_heartbeat_details (2 .temporal.api.common.v1.Payloads"[
%RespondActivityTaskFailedByIdResponse2
failures (2 .temporal.api.failure.v1.Failure"‘
"RespondActivityTaskCanceledRequest

task_token (1
details (2 .temporal.api.common.v1.Payloads
identity (	
	namespace (	B
worker_version (2*.temporal.api.common.v1.WorkerVersionStamp"%
#RespondActivityTaskCanceledResponse"∫
&RespondActivityTaskCanceledByIdRequest
	namespace (	
workflow_id (	
run_id (	
activity_id (	1
details (2 .temporal.api.common.v1.Payloads
identity (	")
\'RespondActivityTaskCanceledByIdResponse"◊
%RequestCancelWorkflowExecutionRequest
	namespace (	E
workflow_execution (2).temporal.api.common.v1.WorkflowExecution
identity (	

request_id (	
first_execution_run_id (	
reason (	"(
&RequestCancelWorkflowExecutionResponse"Ã
SignalWorkflowExecutionRequest
	namespace (	E
workflow_execution (2).temporal.api.common.v1.WorkflowExecution
signal_name (	/
input (2 .temporal.api.common.v1.Payloads
identity (	

request_id (	
control (	.
header (2.temporal.api.common.v1.Header#
skip_generate_workflow_task	 ("!
SignalWorkflowExecutionResponse"Ë
\'SignalWithStartWorkflowExecutionRequest
	namespace (	
workflow_id (	;
workflow_type (2$.temporal.api.common.v1.WorkflowType8

task_queue (2$.temporal.api.taskqueue.v1.TaskQueue/
input (2 .temporal.api.common.v1.PayloadsC
workflow_execution_timeout (2.google.protobuf.DurationBòﬂ=
workflow_run_timeout (2.google.protobuf.DurationBòﬂ>
workflow_task_timeout (2.google.protobuf.DurationBòﬂ
identity	 (	

request_id
 (	N
workflow_id_reuse_policy (2,.temporal.api.enums.v1.WorkflowIdReusePolicy
signal_name (	6
signal_input (2 .temporal.api.common.v1.Payloads
control (	9
retry_policy (2#.temporal.api.common.v1.RetryPolicy
cron_schedule (	*
memo (2.temporal.api.common.v1.MemoC
search_attributes (2(.temporal.api.common.v1.SearchAttributes.
header (2.temporal.api.common.v1.Header=
workflow_start_delay (2.google.protobuf.DurationBòﬂ#
skip_generate_workflow_task (":
(SignalWithStartWorkflowExecutionResponse
run_id (	"â
ResetWorkflowExecutionRequest
	namespace (	E
workflow_execution (2).temporal.api.common.v1.WorkflowExecution
reason (	%
workflow_task_finish_event_id (

request_id (	C
reset_reapply_type (2\'.temporal.api.enums.v1.ResetReapplyType"0
ResetWorkflowExecutionResponse
run_id (	"Ú
!TerminateWorkflowExecutionRequest
	namespace (	E
workflow_execution (2).temporal.api.common.v1.WorkflowExecution
reason (	1
details (2 .temporal.api.common.v1.Payloads
identity (	
first_execution_run_id (	"$
"TerminateWorkflowExecutionResponse"z
DeleteWorkflowExecutionRequest
	namespace (	E
workflow_execution (2).temporal.api.common.v1.WorkflowExecution"!
DeleteWorkflowExecutionResponse"…
!ListOpenWorkflowExecutionsRequest
	namespace (	
maximum_page_size (
next_page_token (B
start_time_filter (2\'.temporal.api.filter.v1.StartTimeFilterK
execution_filter (2/.temporal.api.filter.v1.WorkflowExecutionFilterH A
type_filter (2*.temporal.api.filter.v1.WorkflowTypeFilterH B	
filters"Ç
"ListOpenWorkflowExecutionsResponseC

executions (2/.temporal.api.workflow.v1.WorkflowExecutionInfo
next_page_token ("ä
#ListClosedWorkflowExecutionsRequest
	namespace (	
maximum_page_size (
next_page_token (B
start_time_filter (2\'.temporal.api.filter.v1.StartTimeFilterK
execution_filter (2/.temporal.api.filter.v1.WorkflowExecutionFilterH A
type_filter (2*.temporal.api.filter.v1.WorkflowTypeFilterH =
status_filter (2$.temporal.api.filter.v1.StatusFilterH B	
filters"Ñ
$ListClosedWorkflowExecutionsResponseC

executions (2/.temporal.api.workflow.v1.WorkflowExecutionInfo
next_page_token ("m
ListWorkflowExecutionsRequest
	namespace (	
	page_size (
next_page_token (
query (	"~
ListWorkflowExecutionsResponseC

executions (2/.temporal.api.workflow.v1.WorkflowExecutionInfo
next_page_token ("u
%ListArchivedWorkflowExecutionsRequest
	namespace (	
	page_size (
next_page_token (
query (	"Ü
&ListArchivedWorkflowExecutionsResponseC

executions (2/.temporal.api.workflow.v1.WorkflowExecutionInfo
next_page_token ("m
ScanWorkflowExecutionsRequest
	namespace (	
	page_size (
next_page_token (
query (	"~
ScanWorkflowExecutionsResponseC

executions (2/.temporal.api.workflow.v1.WorkflowExecutionInfo
next_page_token ("B
CountWorkflowExecutionsRequest
	namespace (	
query (	"0
CountWorkflowExecutionsResponse
count ("
GetSearchAttributesRequest"…
GetSearchAttributesResponseT
keys (2F.temporal.api.workflowservice.v1.GetSearchAttributesResponse.KeysEntryT
	KeysEntry
key (	6
value (2\'.temporal.api.enums.v1.IndexedValueType:8"ﬁ
 RespondQueryTaskCompletedRequest

task_token (>
completed_type (2&.temporal.api.enums.v1.QueryResultType6
query_result (2 .temporal.api.common.v1.Payloads
error_message (	
	namespace (	J"#
!RespondQueryTaskCompletedResponse"n
ResetStickyTaskQueueRequest
	namespace (	<
	execution (2).temporal.api.common.v1.WorkflowExecution"
ResetStickyTaskQueueResponse"È
QueryWorkflowRequest
	namespace (	<
	execution (2).temporal.api.common.v1.WorkflowExecution3
query (2$.temporal.api.query.v1.WorkflowQueryK
query_reject_condition (2+.temporal.api.enums.v1.QueryRejectCondition"ç
QueryWorkflowResponse6
query_result (2 .temporal.api.common.v1.Payloads<
query_rejected (2$.temporal.api.query.v1.QueryRejected"s
 DescribeWorkflowExecutionRequest
	namespace (	<
	execution (2).temporal.api.common.v1.WorkflowExecution"Æ
!DescribeWorkflowExecutionResponseK
execution_config (21.temporal.api.workflow.v1.WorkflowExecutionConfigP
workflow_execution_info (2/.temporal.api.workflow.v1.WorkflowExecutionInfoI
pending_activities (2-.temporal.api.workflow.v1.PendingActivityInfoM
pending_children (23.temporal.api.workflow.v1.PendingChildExecutionInfoP
pending_workflow_task (21.temporal.api.workflow.v1.PendingWorkflowTaskInfo"…
DescribeTaskQueueRequest
	namespace (	8

task_queue (2$.temporal.api.taskqueue.v1.TaskQueue=
task_queue_type (2$.temporal.api.enums.v1.TaskQueueType!
include_task_queue_status ("ö
DescribeTaskQueueResponse6
pollers (2%.temporal.api.taskqueue.v1.PollerInfoE
task_queue_status (2*.temporal.api.taskqueue.v1.TaskQueueStatus"
GetClusterInfoRequest"ã
GetClusterInfoResponseh
supported_clients (2M.temporal.api.workflowservice.v1.GetClusterInfoResponse.SupportedClientsEntry
server_version (	

cluster_id (	:
version_info (2$.temporal.api.version.v1.VersionInfo
cluster_name (	
history_shard_count (
persistence_store (	
visibility_store (	7
SupportedClientsEntry
key (	
value (	:8"
GetSystemInfoRequest"º
GetSystemInfoResponse
server_version (	Y
capabilities (2C.temporal.api.workflowservice.v1.GetSystemInfoResponse.CapabilitiesØ
Capabilities
signal_and_query_header (&
internal_error_differentiation (*
"activity_failure_include_heartbeat (
supports_schedules ("
encoded_failure_attributes (!
build_id_based_versioning (
upsert_memo (
eager_workflow_start (
sdk_metadata	 ("m
ListTaskQueuePartitionsRequest
	namespace (	8

task_queue (2$.temporal.api.taskqueue.v1.TaskQueue"ﬂ
ListTaskQueuePartitionsResponse]
activity_task_queue_partitions (25.temporal.api.taskqueue.v1.TaskQueuePartitionMetadata]
workflow_task_queue_partitions (25.temporal.api.taskqueue.v1.TaskQueuePartitionMetadata"Ã
CreateScheduleRequest
	namespace (	
schedule_id (	4
schedule (2".temporal.api.schedule.v1.Schedule>
initial_patch (2\'.temporal.api.schedule.v1.SchedulePatch
identity (	

request_id (	*
memo (2.temporal.api.common.v1.MemoC
search_attributes (2(.temporal.api.common.v1.SearchAttributes"0
CreateScheduleResponse
conflict_token ("A
DescribeScheduleRequest
	namespace (	
schedule_id (	"è
DescribeScheduleResponse4
schedule (2".temporal.api.schedule.v1.Schedule4
info (2&.temporal.api.schedule.v1.ScheduleInfo*
memo (2.temporal.api.common.v1.MemoC
search_attributes (2(.temporal.api.common.v1.SearchAttributes
conflict_token ("≥
UpdateScheduleRequest
	namespace (	
schedule_id (	4
schedule (2".temporal.api.schedule.v1.Schedule
conflict_token (
identity (	

request_id (	"
UpdateScheduleResponse"ú
PatchScheduleRequest
	namespace (	
schedule_id (	6
patch (2\'.temporal.api.schedule.v1.SchedulePatch
identity (	

request_id (	"
PatchScheduleResponse"¥
 ListScheduleMatchingTimesRequest
	namespace (	
schedule_id (	4

start_time (2.google.protobuf.TimestampBêﬂ2
end_time (2.google.protobuf.TimestampBêﬂ"Y
!ListScheduleMatchingTimesResponse4

start_time (2.google.protobuf.TimestampBêﬂ"Q
DeleteScheduleRequest
	namespace (	
schedule_id (	
identity (	"
DeleteScheduleResponse"]
ListSchedulesRequest
	namespace (	
maximum_page_size (
next_page_token ("p
ListSchedulesResponse>
	schedules (2+.temporal.api.schedule.v1.ScheduleListEntry
next_page_token ("Ü
\'UpdateWorkerBuildIdCompatibilityRequest
	namespace (	

task_queue (	-
#add_new_build_id_in_new_default_set (	H á
add_new_compatible_build_id (2`.temporal.api.workflowservice.v1.UpdateWorkerBuildIdCompatibilityRequest.AddNewCompatibleVersionH !
promote_set_by_build_id (	H %
promote_build_id_within_set (	H h

merge_sets (2R.temporal.api.workflowservice.v1.UpdateWorkerBuildIdCompatibilityRequest.MergeSetsH o
AddNewCompatibleVersion
new_build_id (	$
existing_compatible_build_id (	
make_set_default (I
	MergeSets
primary_set_build_id (	
secondary_set_build_id (	B
	operation"B
(UpdateWorkerBuildIdCompatibilityResponse
version_set_id (	"_
$GetWorkerBuildIdCompatibilityRequest
	namespace (	

task_queue (	
max_sets ("t
%GetWorkerBuildIdCompatibilityResponseK
major_version_sets (2/.temporal.api.taskqueue.v1.CompatibleVersionSet"ú
 GetWorkerTaskReachabilityRequest
	namespace (	
	build_ids (	
task_queues (	=
reachability (2\'.temporal.api.enums.v1.TaskReachability"r
!GetWorkerTaskReachabilityResponseM
build_id_reachability (2..temporal.api.taskqueue.v1.BuildIdReachability"Ö
UpdateWorkflowExecutionRequest
	namespace (	E
workflow_execution (2).temporal.api.common.v1.WorkflowExecution
first_execution_run_id (	7
wait_policy (2".temporal.api.update.v1.WaitPolicy0
request (2.temporal.api.update.v1.Request"ä
UpdateWorkflowExecutionResponse5

update_ref (2!.temporal.api.update.v1.UpdateRef0
outcome (2.temporal.api.update.v1.Outcome"∫
StartBatchOperationRequest
	namespace (	
visibility_query (	
job_id (	
reason (	=

executions (2).temporal.api.common.v1.WorkflowExecutionQ
termination_operation
 (20.temporal.api.batch.v1.BatchOperationTerminationH G
signal_operation (2+.temporal.api.batch.v1.BatchOperationSignalH S
cancellation_operation (21.temporal.api.batch.v1.BatchOperationCancellationH K
deletion_operation (2-.temporal.api.batch.v1.BatchOperationDeletionH E
reset_operation (2*.temporal.api.batch.v1.BatchOperationResetH B
	operation"
StartBatchOperationResponse"`
StopBatchOperationRequest
	namespace (	
job_id (	
reason (	
identity (	"
StopBatchOperationResponse"B
DescribeBatchOperationRequest
	namespace (	
job_id (	"û
DescribeBatchOperationResponseA
operation_type (2).temporal.api.enums.v1.BatchOperationType
job_id (	9
state (2*.temporal.api.enums.v1.BatchOperationState4

start_time (2.google.protobuf.TimestampBêﬂ4

close_time (2.google.protobuf.TimestampBêﬂ
total_operation_count ( 
complete_operation_count (
failure_operation_count (
identity	 (	
reason
 (	"[
ListBatchOperationsRequest
	namespace (	
	page_size (
next_page_token ("y
ListBatchOperationsResponseA
operation_info (2).temporal.api.batch.v1.BatchOperationInfo
next_page_token ("π
"PollWorkflowExecutionUpdateRequest
	namespace (	5

update_ref (2!.temporal.api.update.v1.UpdateRef
identity (	7
wait_policy (2".temporal.api.update.v1.WaitPolicy"W
#PollWorkflowExecutionUpdateResponse0
outcome (2.temporal.api.update.v1.OutcomeBæ
"io.temporal.api.workflowservice.v1BRequestResponseProtoPZ5go.temporal.io/api/workflowservice/v1;workflowservice™!Temporalio.Api.WorkflowService.V1Í$Temporalio::Api::WorkflowService::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

