<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/operatorservice/v1/request_response.proto

namespace GPBMetadata\Temporal\Api\Operatorservice\V1;

class RequestResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Temporal\Api\Enums\V1\Common::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ž

6temporal/api/operatorservice/v1/request_response.prototemporal.api.operatorservice.v1"ì
AddSearchAttributesRequestl
search_attributes (2Q.temporal.api.operatorservice.v1.AddSearchAttributesRequest.SearchAttributesEntry`
SearchAttributesEntry
key (	6
value (2\'.temporal.api.enums.v1.IndexedValueType:8"
AddSearchAttributesResponse":
RemoveSearchAttributesRequest
search_attributes (	" 
RemoveSearchAttributesResponse"
ListSearchAttributesRequest"â
ListSearchAttributesResponsen
custom_attributes (2S.temporal.api.operatorservice.v1.ListSearchAttributesResponse.CustomAttributesEntryn
system_attributes (2S.temporal.api.operatorservice.v1.ListSearchAttributesResponse.SystemAttributesEntryh
storage_schema (2P.temporal.api.operatorservice.v1.ListSearchAttributesResponse.StorageSchemaEntry`
CustomAttributesEntry
key (	6
value (2\'.temporal.api.enums.v1.IndexedValueType:8`
SystemAttributesEntry
key (	6
value (2\'.temporal.api.enums.v1.IndexedValueType:84
StorageSchemaEntry
key (	
value (	:8Bº
"io.temporal.api.operatorservice.v1BRequestResponseProtoPZ5go.temporal.io/api/operatorservice/v1;operatorserviceªTemporal.Api.OperatorService.V1ê"Temporal::Api::OperatorService::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

