<?php

declare(strict_types=1);

namespace Temporal\Tests\Unit\Nexus;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use Temporal\Nexus\Internal\WorkflowRunOperationToken;
use Temporal\Tests\Unit\AbstractUnit;

/**
 * @group unit
 * @group nexus
 */
#[CoversClass(WorkflowRunOperationToken::class)]
final class WorkflowRunOperationTokenTestCase extends AbstractUnit
{
    /**
     * Golden vectors generated by the Go reference at
     * `sdk-go/temporalnexus/token.go::generateWorkflowRunOperationToken` —
     * the wire format must stay byte-identical so PHP-issued tokens decode
     * cleanly on a Go-typed handler/server and vice-versa.
     */
    public static function goldenVectors(): array
    {
        return [
            'sample-style' => [
                'namespace' => 'my-target-namespace',
                'workflowId' => 'my-workflow-id',
                'expected' => 'eyJ0IjoxLCJucyI6Im15LXRhcmdldC1uYW1lc3BhY2UiLCJ3aWQiOiJteS13b3JrZmxvdy1pZCJ9',
            ],
            'short' => [
                'namespace' => 'default',
                'workflowId' => 'abc',
                'expected' => 'eyJ0IjoxLCJucyI6ImRlZmF1bHQiLCJ3aWQiOiJhYmMifQ',
            ],
            'special-chars-in-ns' => [
                'namespace' => 'ns-with/special.chars',
                'workflowId' => 'wid-1234',
                'expected' => 'eyJ0IjoxLCJucyI6Im5zLXdpdGgvc3BlY2lhbC5jaGFycyIsIndpZCI6IndpZC0xMjM0In0',
            ],
            'both-empty' => [
                'namespace' => '',
                'workflowId' => '',
                'expected' => 'eyJ0IjoxLCJucyI6IiIsIndpZCI6IiJ9',
            ],
        ];
    }

    #[DataProvider('goldenVectors')]
    public function testEncodeMatchesGoReference(string $namespace, string $workflowId, string $expected): void
    {
        self::assertSame($expected, WorkflowRunOperationToken::generate($namespace, $workflowId));
    }

    public function testRoundtripWorkflowIdAndNamespace(): void
    {
        $token = WorkflowRunOperationToken::generate('ns-A', 'wf-42');
        $decoded = WorkflowRunOperationToken::load($token);

        self::assertSame('ns-A', $decoded->namespace);
        self::assertSame('wf-42', $decoded->workflowId);
    }

    public function testLoadRejectsEmptyToken(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('token is empty');
        WorkflowRunOperationToken::load('');
    }

    public function testLoadRejectsBadBase64(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('failed to decode token');
        WorkflowRunOperationToken::load('!!!not-base64!!!');
    }

    public function testLoadRejectsNonJson(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('failed to unmarshal');
        // base64 of "not-json"
        WorkflowRunOperationToken::load('bm90LWpzb24');
    }

    public function testLoadRejectsWrongType(): void
    {
        // {"t":2,"ns":"x","wid":"y"} — t=2 is not workflow-run
        $bad = \rtrim(\strtr(\base64_encode('{"t":2,"ns":"x","wid":"y"}'), '+/', '-_'), '=');

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('invalid workflow token type');
        WorkflowRunOperationToken::load($bad);
    }

    public function testLoadRejectsMissingWorkflowId(): void
    {
        // {"t":1,"ns":"x"} — wid missing
        $bad = \rtrim(\strtr(\base64_encode('{"t":1,"ns":"x"}'), '+/', '-_'), '=');

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('missing workflow ID');
        WorkflowRunOperationToken::load($bad);
    }

    public function testLoadRejectsExplicitVersionField(): void
    {
        // {"v":2,"t":1,"ns":"x","wid":"y"} — v present and non-zero
        $bad = \rtrim(\strtr(\base64_encode('{"v":2,"t":1,"ns":"x","wid":"y"}'), '+/', '-_'), '=');

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('unsupported version');
        WorkflowRunOperationToken::load($bad);
    }

    public function testLoadAcceptsExplicitVersionZero(): void
    {
        // {"v":0,"t":1,"ns":"x","wid":"y"} — v=0 is the implicit default,
        // accepted by the Go reference even when explicitly written out.
        $ok = \rtrim(\strtr(\base64_encode('{"v":0,"t":1,"ns":"x","wid":"y"}'), '+/', '-_'), '=');

        $decoded = WorkflowRunOperationToken::load($ok);

        self::assertSame('x', $decoded->namespace);
        self::assertSame('y', $decoded->workflowId);
    }
}
