<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/operatorservice/v1/request_response.proto

namespace Temporal\Api\Operatorservice\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.operatorservice.v1.ListSearchAttributesResponse</code>
 */
class ListSearchAttributesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Mapping between custom (user-registered) search attribute name to its IndexedValueType.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> custom_attributes = 1;</code>
     */
    private $custom_attributes;
    /**
     * Mapping between system (predefined) search attribute name to its IndexedValueType.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> system_attributes = 2;</code>
     */
    private $system_attributes;
    /**
     * Mapping from the attribute name to the visibility storage native type
     *
     * Generated from protobuf field <code>map<string, string> storage_schema = 3;</code>
     */
    private $storage_schema;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $custom_attributes
     *           Mapping between custom (user-registered) search attribute name to its IndexedValueType.
     *     @type array|\Google\Protobuf\Internal\MapField $system_attributes
     *           Mapping between system (predefined) search attribute name to its IndexedValueType.
     *     @type array|\Google\Protobuf\Internal\MapField $storage_schema
     *           Mapping from the attribute name to the visibility storage native type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Operatorservice\V1\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Mapping between custom (user-registered) search attribute name to its IndexedValueType.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> custom_attributes = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCustomAttributes()
    {
        return $this->custom_attributes;
    }

    /**
     * Mapping between custom (user-registered) search attribute name to its IndexedValueType.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> custom_attributes = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCustomAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::ENUM, \Temporal\Api\Enums\V1\IndexedValueType::class);
        $this->custom_attributes = $arr;

        return $this;
    }

    /**
     * Mapping between system (predefined) search attribute name to its IndexedValueType.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> system_attributes = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSystemAttributes()
    {
        return $this->system_attributes;
    }

    /**
     * Mapping between system (predefined) search attribute name to its IndexedValueType.
     *
     * Generated from protobuf field <code>map<string, .temporal.api.enums.v1.IndexedValueType> system_attributes = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSystemAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::ENUM, \Temporal\Api\Enums\V1\IndexedValueType::class);
        $this->system_attributes = $arr;

        return $this;
    }

    /**
     * Mapping from the attribute name to the visibility storage native type
     *
     * Generated from protobuf field <code>map<string, string> storage_schema = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getStorageSchema()
    {
        return $this->storage_schema;
    }

    /**
     * Mapping from the attribute name to the visibility storage native type
     *
     * Generated from protobuf field <code>map<string, string> storage_schema = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setStorageSchema($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->storage_schema = $arr;

        return $this;
    }

}

