<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/update/v1/message.proto

namespace Temporal\Api\Update\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Specifies to the gRPC server how long the client wants the an update-related
 * RPC call to wait before returning control to the caller.
 *
 * Generated from protobuf message <code>temporal.api.update.v1.WaitPolicy</code>
 */
class WaitPolicy extends \Google\Protobuf\Internal\Message
{
    /**
     * Indicates the update lifecycle stage that the gRPC call should wait for
     * before returning.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.UpdateWorkflowExecutionLifecycleStage lifecycle_stage = 1;</code>
     */
    protected $lifecycle_stage = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $lifecycle_stage
     *           Indicates the update lifecycle stage that the gRPC call should wait for
     *           before returning.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Update\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Indicates the update lifecycle stage that the gRPC call should wait for
     * before returning.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.UpdateWorkflowExecutionLifecycleStage lifecycle_stage = 1;</code>
     * @return int
     */
    public function getLifecycleStage()
    {
        return $this->lifecycle_stage;
    }

    /**
     * Indicates the update lifecycle stage that the gRPC call should wait for
     * before returning.
     *
     * Generated from protobuf field <code>.temporal.api.enums.v1.UpdateWorkflowExecutionLifecycleStage lifecycle_stage = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLifecycleStage($var)
    {
        GPBUtil::checkEnum($var, \Temporal\Api\Enums\V1\UpdateWorkflowExecutionLifecycleStage::class);
        $this->lifecycle_stage = $var;

        return $this;
    }

}

