<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/enums/v1/workflow.proto

namespace Temporal\Api\Enums\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>temporal.api.enums.v1.HistoryEventFilterType</code>
 */
class HistoryEventFilterType
{
    /**
     * Generated from protobuf enum <code>HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED = 0;</code>
     */
    const HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>HISTORY_EVENT_FILTER_TYPE_ALL_EVENT = 1;</code>
     */
    const HISTORY_EVENT_FILTER_TYPE_ALL_EVENT = 1;
    /**
     * Generated from protobuf enum <code>HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT = 2;</code>
     */
    const HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT = 2;

    private static $valueToName = [
        self::HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED => 'HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED',
        self::HISTORY_EVENT_FILTER_TYPE_ALL_EVENT => 'HISTORY_EVENT_FILTER_TYPE_ALL_EVENT',
        self::HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT => 'HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

