on:
  push:
    branches:
      - '*'

name: Fix Code Style

jobs:
  cs-fix:
    permissions:
      contents: write
    uses: spiral/gh-actions/.github/workflows/cs-fix.yml@e966c298913edde0d254c9afdbb07a7f4f3d3acc
