name: Security

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}
  group: tests-${{ github.workflow }}-${{ github.ref }}

jobs:
  security:
    name: Security Checks (PHP ${{ matrix.php }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Note: This workflow requires only the LATEST version of PHP
        php: [ 8.2 ]
        os: [ ubuntu-latest ]
    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, sockets, grpc, curl

      - name: Check Out Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install dependencies with composer
        uses: ramsey/composer-install@5c2bcf28d7b060ef3c601d7b476d5430a7b46c27 # v4
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Verify
        run: composer require --dev roave/security-advisories:dev-latest
